export const ROUTES = {
  "/locales": "locales",
  "/user": "user",
  "/api-keys": "apiKeys",
  "/projects-m": "projectsM",
  "/todo-list": "todoList",
  "/calendar": "calendar",
  "/idea-box": "ideaBox",
  "/code-time": "codeTime",
  "/books-library": "booksLibrary",
  "/achievements": "achievements",
  "/wallet": "wallet",
  "/wishlist": "wishlist",
  "/music": "music",
  "/guitar-tabs": "guitarTabs",
  "/youtube-videos": "youtubeVideos",
  "/passwords": "passwords",
  "/sudoku": "sudoku",
  "/server": "server",
  "/pixabay": "pixabay",
  "/quotes": "quotes",
  "/virtual-wardrobe": "virtualWardrobe",
  "/moment-vault": "momentVault/routes",
  "/movies": "movies",
  "/railway-map": "railwayMap",
  "/locations": "locations",
};
